// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.springsource.roo.inspect.domain;

import com.springsource.roo.inspect.domain.Dept;
import com.springsource.roo.inspect.domain.DeptDataOnDemand;
import com.springsource.roo.inspect.domain.DeptIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect DeptIntegrationTest_Roo_IntegrationTest {
    
    declare @type: DeptIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: DeptIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: DeptIntegrationTest: @Transactional;
    
    @Autowired
    DeptDataOnDemand DeptIntegrationTest.dod;
    
    @Test
    public void DeptIntegrationTest.testCountDepts() {
        Assert.assertNotNull("Data on demand for 'Dept' failed to initialize correctly", dod.getRandomDept());
        long count = Dept.countDepts();
        Assert.assertTrue("Counter for 'Dept' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void DeptIntegrationTest.testFindDept() {
        Dept obj = dod.getRandomDept();
        Assert.assertNotNull("Data on demand for 'Dept' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Dept' failed to provide an identifier", id);
        obj = Dept.findDept(id);
        Assert.assertNotNull("Find method for 'Dept' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Dept' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void DeptIntegrationTest.testFindAllDepts() {
        Assert.assertNotNull("Data on demand for 'Dept' failed to initialize correctly", dod.getRandomDept());
        long count = Dept.countDepts();
        Assert.assertTrue("Too expensive to perform a find all test for 'Dept', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Dept> result = Dept.findAllDepts();
        Assert.assertNotNull("Find all method for 'Dept' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Dept' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void DeptIntegrationTest.testFindDeptEntries() {
        Assert.assertNotNull("Data on demand for 'Dept' failed to initialize correctly", dod.getRandomDept());
        long count = Dept.countDepts();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Dept> result = Dept.findDeptEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Dept' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Dept' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void DeptIntegrationTest.testFlush() {
        Dept obj = dod.getRandomDept();
        Assert.assertNotNull("Data on demand for 'Dept' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Dept' failed to provide an identifier", id);
        obj = Dept.findDept(id);
        Assert.assertNotNull("Find method for 'Dept' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyDept(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Dept' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void DeptIntegrationTest.testMergeUpdate() {
        Dept obj = dod.getRandomDept();
        Assert.assertNotNull("Data on demand for 'Dept' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Dept' failed to provide an identifier", id);
        obj = Dept.findDept(id);
        boolean modified =  dod.modifyDept(obj);
        Integer currentVersion = obj.getVersion();
        Dept merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Dept' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void DeptIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Dept' failed to initialize correctly", dod.getRandomDept());
        Dept obj = dod.getNewTransientDept(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Dept' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Dept' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Dept' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void DeptIntegrationTest.testRemove() {
        Dept obj = dod.getRandomDept();
        Assert.assertNotNull("Data on demand for 'Dept' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Dept' failed to provide an identifier", id);
        obj = Dept.findDept(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Dept' with identifier '" + id + "'", Dept.findDept(id));
    }
    
}
