// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.springsource.roo.inspect.domain;

import com.springsource.roo.inspect.domain.Dept;
import com.springsource.roo.inspect.domain.DeptDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect DeptDataOnDemand_Roo_DataOnDemand {
    
    declare @type: DeptDataOnDemand: @Component;
    
    private Random DeptDataOnDemand.rnd = new SecureRandom();
    
    private List<Dept> DeptDataOnDemand.data;
    
    public Dept DeptDataOnDemand.getNewTransientDept(int index) {
        Dept obj = new Dept();
        setCreatetime(obj, index);
        setDescription(obj, index);
        setName(obj, index);
        return obj;
    }
    
    public void DeptDataOnDemand.setCreatetime(Dept obj, int index) {
        Date createtime = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreatetime(createtime);
    }
    
    public void DeptDataOnDemand.setDescription(Dept obj, int index) {
        String description = "descriptionxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx_" + index;
        obj.setDescription(description);
    }
    
    public void DeptDataOnDemand.setName(Dept obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public Dept DeptDataOnDemand.getSpecificDept(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Dept obj = data.get(index);
        Long id = obj.getId();
        return Dept.findDept(id);
    }
    
    public Dept DeptDataOnDemand.getRandomDept() {
        init();
        Dept obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Dept.findDept(id);
    }
    
    public boolean DeptDataOnDemand.modifyDept(Dept obj) {
        return false;
    }
    
    public void DeptDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Dept.findDeptEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Dept' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Dept>();
        for (int i = 0; i < 10; i++) {
            Dept obj = getNewTransientDept(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
