// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.springsource.roo.inspect.domain;

import com.springsource.roo.inspect.domain.Device;
import com.springsource.roo.inspect.domain.DeviceDataOnDemand;
import com.springsource.roo.inspect.domain.DeviceIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect DeviceIntegrationTest_Roo_IntegrationTest {
    
    declare @type: DeviceIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: DeviceIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: DeviceIntegrationTest: @Transactional;
    
    @Autowired
    DeviceDataOnDemand DeviceIntegrationTest.dod;
    
    @Test
    public void DeviceIntegrationTest.testCountDevices() {
        Assert.assertNotNull("Data on demand for 'Device' failed to initialize correctly", dod.getRandomDevice());
        long count = Device.countDevices();
        Assert.assertTrue("Counter for 'Device' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void DeviceIntegrationTest.testFindDevice() {
        Device obj = dod.getRandomDevice();
        Assert.assertNotNull("Data on demand for 'Device' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Device' failed to provide an identifier", id);
        obj = Device.findDevice(id);
        Assert.assertNotNull("Find method for 'Device' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Device' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void DeviceIntegrationTest.testFindAllDevices() {
        Assert.assertNotNull("Data on demand for 'Device' failed to initialize correctly", dod.getRandomDevice());
        long count = Device.countDevices();
        Assert.assertTrue("Too expensive to perform a find all test for 'Device', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Device> result = Device.findAllDevices();
        Assert.assertNotNull("Find all method for 'Device' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Device' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void DeviceIntegrationTest.testFindDeviceEntries() {
        Assert.assertNotNull("Data on demand for 'Device' failed to initialize correctly", dod.getRandomDevice());
        long count = Device.countDevices();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Device> result = Device.findDeviceEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Device' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Device' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void DeviceIntegrationTest.testFlush() {
        Device obj = dod.getRandomDevice();
        Assert.assertNotNull("Data on demand for 'Device' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Device' failed to provide an identifier", id);
        obj = Device.findDevice(id);
        Assert.assertNotNull("Find method for 'Device' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyDevice(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Device' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void DeviceIntegrationTest.testMergeUpdate() {
        Device obj = dod.getRandomDevice();
        Assert.assertNotNull("Data on demand for 'Device' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Device' failed to provide an identifier", id);
        obj = Device.findDevice(id);
        boolean modified =  dod.modifyDevice(obj);
        Integer currentVersion = obj.getVersion();
        Device merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Device' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void DeviceIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Device' failed to initialize correctly", dod.getRandomDevice());
        Device obj = dod.getNewTransientDevice(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Device' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Device' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Device' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void DeviceIntegrationTest.testRemove() {
        Device obj = dod.getRandomDevice();
        Assert.assertNotNull("Data on demand for 'Device' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Device' failed to provide an identifier", id);
        obj = Device.findDevice(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Device' with identifier '" + id + "'", Device.findDevice(id));
    }
    
}
