// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.springsource.roo.inspect.domain;

import com.springsource.roo.inspect.domain.DeviceDataOnDemand;
import com.springsource.roo.inspect.domain.DeviceInspectRec;
import com.springsource.roo.inspect.domain.DeviceInspectRecDataOnDemand;
import com.springsource.roo.inspect.domain.InspectItemDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect DeviceInspectRecDataOnDemand_Roo_DataOnDemand {
    
    declare @type: DeviceInspectRecDataOnDemand: @Component;
    
    private Random DeviceInspectRecDataOnDemand.rnd = new SecureRandom();
    
    private List<DeviceInspectRec> DeviceInspectRecDataOnDemand.data;
    
    @Autowired
    DeviceDataOnDemand DeviceInspectRecDataOnDemand.deviceDataOnDemand;
    
    @Autowired
    InspectItemDataOnDemand DeviceInspectRecDataOnDemand.inspectItemDataOnDemand;
    
    public DeviceInspectRec DeviceInspectRecDataOnDemand.getNewTransientDeviceInspectRec(int index) {
        DeviceInspectRec obj = new DeviceInspectRec();
        setRvalue(obj, index);
        return obj;
    }
    
    public void DeviceInspectRecDataOnDemand.setRvalue(DeviceInspectRec obj, int index) {
        String rvalue = "rvalue_" + index;
        obj.setRvalue(rvalue);
    }
    
    public DeviceInspectRec DeviceInspectRecDataOnDemand.getSpecificDeviceInspectRec(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        DeviceInspectRec obj = data.get(index);
        Long id = obj.getId();
        return DeviceInspectRec.findDeviceInspectRec(id);
    }
    
    public DeviceInspectRec DeviceInspectRecDataOnDemand.getRandomDeviceInspectRec() {
        init();
        DeviceInspectRec obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return DeviceInspectRec.findDeviceInspectRec(id);
    }
    
    public boolean DeviceInspectRecDataOnDemand.modifyDeviceInspectRec(DeviceInspectRec obj) {
        return false;
    }
    
    public void DeviceInspectRecDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = DeviceInspectRec.findDeviceInspectRecEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'DeviceInspectRec' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<DeviceInspectRec>();
        for (int i = 0; i < 10; i++) {
            DeviceInspectRec obj = getNewTransientDeviceInspectRec(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
