// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.springsource.roo.inspect.domain;

import com.springsource.roo.inspect.domain.InspectItem;
import com.springsource.roo.inspect.domain.InspectItemDataOnDemand;
import com.springsource.roo.inspect.domain.InspectTableDataOnDemand;
import com.springsource.roo.inspect.domain.InspectTagDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect InspectItemDataOnDemand_Roo_DataOnDemand {
    
    declare @type: InspectItemDataOnDemand: @Component;
    
    private Random InspectItemDataOnDemand.rnd = new SecureRandom();
    
    private List<InspectItem> InspectItemDataOnDemand.data;
    
    @Autowired
    InspectTableDataOnDemand InspectItemDataOnDemand.inspectTableDataOnDemand;
    
    @Autowired
    InspectTagDataOnDemand InspectItemDataOnDemand.inspectTagDataOnDemand;
    
    public InspectItem InspectItemDataOnDemand.getNewTransientInspectItem(int index) {
        InspectItem obj = new InspectItem();
        setCreatetime(obj, index);
        setDescription(obj, index);
        setItemvalue(obj, index);
        setName(obj, index);
        setNumbers(obj, index);
        return obj;
    }
    
    public void InspectItemDataOnDemand.setCreatetime(InspectItem obj, int index) {
        Date createtime = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreatetime(createtime);
    }
    
    public void InspectItemDataOnDemand.setDescription(InspectItem obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public void InspectItemDataOnDemand.setItemvalue(InspectItem obj, int index) {
        String itemvalue = "itemvalue_" + index;
        obj.setItemvalue(itemvalue);
    }
    
    public void InspectItemDataOnDemand.setName(InspectItem obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public void InspectItemDataOnDemand.setNumbers(InspectItem obj, int index) {
        String numbers = "numbers_" + index;
        obj.setNumbers(numbers);
    }
    
    public InspectItem InspectItemDataOnDemand.getSpecificInspectItem(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        InspectItem obj = data.get(index);
        Long id = obj.getId();
        return InspectItem.findInspectItem(id);
    }
    
    public InspectItem InspectItemDataOnDemand.getRandomInspectItem() {
        init();
        InspectItem obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return InspectItem.findInspectItem(id);
    }
    
    public boolean InspectItemDataOnDemand.modifyInspectItem(InspectItem obj) {
        return false;
    }
    
    public void InspectItemDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = InspectItem.findInspectItemEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'InspectItem' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<InspectItem>();
        for (int i = 0; i < 10; i++) {
            InspectItem obj = getNewTransientInspectItem(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
