// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.springsource.roo.inspect.domain;

import com.springsource.roo.inspect.domain.InspectItem;
import com.springsource.roo.inspect.domain.InspectItemDataOnDemand;
import com.springsource.roo.inspect.domain.InspectItemIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect InspectItemIntegrationTest_Roo_IntegrationTest {
    
    declare @type: InspectItemIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: InspectItemIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: InspectItemIntegrationTest: @Transactional;
    
    @Autowired
    InspectItemDataOnDemand InspectItemIntegrationTest.dod;
    
    @Test
    public void InspectItemIntegrationTest.testCountInspectItems() {
        Assert.assertNotNull("Data on demand for 'InspectItem' failed to initialize correctly", dod.getRandomInspectItem());
        long count = InspectItem.countInspectItems();
        Assert.assertTrue("Counter for 'InspectItem' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void InspectItemIntegrationTest.testFindInspectItem() {
        InspectItem obj = dod.getRandomInspectItem();
        Assert.assertNotNull("Data on demand for 'InspectItem' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'InspectItem' failed to provide an identifier", id);
        obj = InspectItem.findInspectItem(id);
        Assert.assertNotNull("Find method for 'InspectItem' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'InspectItem' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void InspectItemIntegrationTest.testFindAllInspectItems() {
        Assert.assertNotNull("Data on demand for 'InspectItem' failed to initialize correctly", dod.getRandomInspectItem());
        long count = InspectItem.countInspectItems();
        Assert.assertTrue("Too expensive to perform a find all test for 'InspectItem', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<InspectItem> result = InspectItem.findAllInspectItems();
        Assert.assertNotNull("Find all method for 'InspectItem' illegally returned null", result);
        Assert.assertTrue("Find all method for 'InspectItem' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void InspectItemIntegrationTest.testFindInspectItemEntries() {
        Assert.assertNotNull("Data on demand for 'InspectItem' failed to initialize correctly", dod.getRandomInspectItem());
        long count = InspectItem.countInspectItems();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<InspectItem> result = InspectItem.findInspectItemEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'InspectItem' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'InspectItem' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void InspectItemIntegrationTest.testFlush() {
        InspectItem obj = dod.getRandomInspectItem();
        Assert.assertNotNull("Data on demand for 'InspectItem' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'InspectItem' failed to provide an identifier", id);
        obj = InspectItem.findInspectItem(id);
        Assert.assertNotNull("Find method for 'InspectItem' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyInspectItem(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'InspectItem' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void InspectItemIntegrationTest.testMergeUpdate() {
        InspectItem obj = dod.getRandomInspectItem();
        Assert.assertNotNull("Data on demand for 'InspectItem' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'InspectItem' failed to provide an identifier", id);
        obj = InspectItem.findInspectItem(id);
        boolean modified =  dod.modifyInspectItem(obj);
        Integer currentVersion = obj.getVersion();
        InspectItem merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'InspectItem' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void InspectItemIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'InspectItem' failed to initialize correctly", dod.getRandomInspectItem());
        InspectItem obj = dod.getNewTransientInspectItem(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'InspectItem' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'InspectItem' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'InspectItem' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void InspectItemIntegrationTest.testRemove() {
        InspectItem obj = dod.getRandomInspectItem();
        Assert.assertNotNull("Data on demand for 'InspectItem' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'InspectItem' failed to provide an identifier", id);
        obj = InspectItem.findInspectItem(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'InspectItem' with identifier '" + id + "'", InspectItem.findInspectItem(id));
    }
    
}
