// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.springsource.roo.inspect.domain;

import com.springsource.roo.inspect.domain.InspectTag;
import com.springsource.roo.inspect.domain.InspectTagDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect InspectTagDataOnDemand_Roo_DataOnDemand {
    
    declare @type: InspectTagDataOnDemand: @Component;
    
    private Random InspectTagDataOnDemand.rnd = new SecureRandom();
    
    private List<InspectTag> InspectTagDataOnDemand.data;
    
    public InspectTag InspectTagDataOnDemand.getNewTransientInspectTag(int index) {
        InspectTag obj = new InspectTag();
        setCreatetime(obj, index);
        setDescription(obj, index);
        setName(obj, index);
        setNumbers(obj, index);
        return obj;
    }
    
    public void InspectTagDataOnDemand.setCreatetime(InspectTag obj, int index) {
        Date createtime = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreatetime(createtime);
    }
    
    public void InspectTagDataOnDemand.setDescription(InspectTag obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public void InspectTagDataOnDemand.setName(InspectTag obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public void InspectTagDataOnDemand.setNumbers(InspectTag obj, int index) {
        String numbers = "numbers_" + index;
        obj.setNumbers(numbers);
    }
    
    public InspectTag InspectTagDataOnDemand.getSpecificInspectTag(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        InspectTag obj = data.get(index);
        Long id = obj.getId();
        return InspectTag.findInspectTag(id);
    }
    
    public InspectTag InspectTagDataOnDemand.getRandomInspectTag() {
        init();
        InspectTag obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return InspectTag.findInspectTag(id);
    }
    
    public boolean InspectTagDataOnDemand.modifyInspectTag(InspectTag obj) {
        return false;
    }
    
    public void InspectTagDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = InspectTag.findInspectTagEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'InspectTag' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<InspectTag>();
        for (int i = 0; i < 10; i++) {
            InspectTag obj = getNewTransientInspectTag(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
