// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.springsource.roo.inspect.domain;

import com.springsource.roo.inspect.domain.Roles;
import com.springsource.roo.inspect.domain.RolesDataOnDemand;
import com.springsource.roo.inspect.domain.RolesIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect RolesIntegrationTest_Roo_IntegrationTest {
    
    declare @type: RolesIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: RolesIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: RolesIntegrationTest: @Transactional;
    
    @Autowired
    RolesDataOnDemand RolesIntegrationTest.dod;
    
    @Test
    public void RolesIntegrationTest.testCountRoleses() {
        Assert.assertNotNull("Data on demand for 'Roles' failed to initialize correctly", dod.getRandomRoles());
        long count = Roles.countRoleses();
        Assert.assertTrue("Counter for 'Roles' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void RolesIntegrationTest.testFindRoles() {
        Roles obj = dod.getRandomRoles();
        Assert.assertNotNull("Data on demand for 'Roles' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Roles' failed to provide an identifier", id);
        obj = Roles.findRoles(id);
        Assert.assertNotNull("Find method for 'Roles' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Roles' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void RolesIntegrationTest.testFindAllRoleses() {
        Assert.assertNotNull("Data on demand for 'Roles' failed to initialize correctly", dod.getRandomRoles());
        long count = Roles.countRoleses();
        Assert.assertTrue("Too expensive to perform a find all test for 'Roles', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Roles> result = Roles.findAllRoleses();
        Assert.assertNotNull("Find all method for 'Roles' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Roles' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void RolesIntegrationTest.testFindRolesEntries() {
        Assert.assertNotNull("Data on demand for 'Roles' failed to initialize correctly", dod.getRandomRoles());
        long count = Roles.countRoleses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Roles> result = Roles.findRolesEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Roles' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Roles' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void RolesIntegrationTest.testFlush() {
        Roles obj = dod.getRandomRoles();
        Assert.assertNotNull("Data on demand for 'Roles' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Roles' failed to provide an identifier", id);
        obj = Roles.findRoles(id);
        Assert.assertNotNull("Find method for 'Roles' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyRoles(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Roles' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RolesIntegrationTest.testMergeUpdate() {
        Roles obj = dod.getRandomRoles();
        Assert.assertNotNull("Data on demand for 'Roles' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Roles' failed to provide an identifier", id);
        obj = Roles.findRoles(id);
        boolean modified =  dod.modifyRoles(obj);
        Integer currentVersion = obj.getVersion();
        Roles merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Roles' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RolesIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Roles' failed to initialize correctly", dod.getRandomRoles());
        Roles obj = dod.getNewTransientRoles(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Roles' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Roles' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Roles' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void RolesIntegrationTest.testRemove() {
        Roles obj = dod.getRandomRoles();
        Assert.assertNotNull("Data on demand for 'Roles' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Roles' failed to provide an identifier", id);
        obj = Roles.findRoles(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Roles' with identifier '" + id + "'", Roles.findRoles(id));
    }
    
}
