// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.springsource.roo.inspect.domain;

import com.springsource.roo.inspect.domain.Roles;
import com.springsource.roo.inspect.domain.RolesDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect RolesDataOnDemand_Roo_DataOnDemand {
    
    declare @type: RolesDataOnDemand: @Component;
    
    private Random RolesDataOnDemand.rnd = new SecureRandom();
    
    private List<Roles> RolesDataOnDemand.data;
    
    public Roles RolesDataOnDemand.getNewTransientRoles(int index) {
        Roles obj = new Roles();
        setCreatetime(obj, index);
        setRolename(obj, index);
        return obj;
    }
    
    public void RolesDataOnDemand.setCreatetime(Roles obj, int index) {
        Date createtime = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreatetime(createtime);
    }
    
    public void RolesDataOnDemand.setRolename(Roles obj, int index) {
        String rolename = "rolename_" + index;
        obj.setRolename(rolename);
    }
    
    public Roles RolesDataOnDemand.getSpecificRoles(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Roles obj = data.get(index);
        Long id = obj.getId();
        return Roles.findRoles(id);
    }
    
    public Roles RolesDataOnDemand.getRandomRoles() {
        init();
        Roles obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Roles.findRoles(id);
    }
    
    public boolean RolesDataOnDemand.modifyRoles(Roles obj) {
        return false;
    }
    
    public void RolesDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Roles.findRolesEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Roles' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Roles>();
        for (int i = 0; i < 10; i++) {
            Roles obj = getNewTransientRoles(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
